### ISSUE TITLE
Grouping of repositories (feature request)

### ISSUE THREAD

**Issue by pfrandsen** [etsy/Hound#102] opened 2015-04-01 08:55 UTC
It would be nice to be able to group indexed repositories via labels (or a fixed hierarchy in the config file). These labels could then be used to include/exclude a set of repositories in specific searches (when you have say 100 repositories selecting repositories for specific searches can be quite tedious). E.g., you could search the repositories belonging to a specific business unit, search all the repositories containing ReST services etc.

Labels would be much preferable to a fixed hierarchy as it allows for multiple categorizations.

Example config.json file:

```javascript
{
    "dbpath" : "data",
    "repos" : {
        "SomeGitRepo" : {
            "url" : "https://www.github.com/YourOrganization/RepoOne.git",
            "labels" : ["label a", "label b"]
        },
        "AnotherGitRepo" : {
            "url" : "https://www.github.com/YourOrganization/RepoOne.git",
            "ms-between-poll": 10000,
            "labels" : ["label a", "label c"]
        }
    }
}
```

**Comment by jklein** [comment] 2015-04-01 14:19
This is a duplicate of #97 - it's a good idea though.

**Closed by jklein** 2015-04-01 14:19 UTC

**Comment by pfrandsen** [comment] 2015-04-01 14:36
Sorry, didn't see #97 - obviously the same problem ;-)
