### ISSUE TITLE
Links to source code don't work for bitbucket repos

### ISSUE THREAD

**Issue by zzztimbo** [etsy/hound#145] opened 2015-07-21 02:08 UTC
I added a private bitbucket repo and none of the links out work. 
I've tried this with a public github repo and that works just fine.

**Comment by jklein** [comment] 2015-07-22 01:16
Have you tried the url-pattern config as specified in the example?

https://github.com/etsy/hound/blob/master/config-example.json#L38-L44

**Comment by gwindes** [comment] 2015-08-04 01:29
Seems like the new bitbucket line numbering link is breaking.

Ex: http://bitbucket.org/reponame/src/rev/.hgignore#.hgignore-56

however using something like:
```
"url-pattern": {
  "anchor": "#{path}-{line}",
  "base-url": "{url}/src/{rev}/{path}{anchor}"
},
```
generates this url : http://bitbucket.org/reponame/src/rev/.hgignore#{path}-56
instead of having the file path it outputs #{path} is there a way to escape the # so it doesn't affect the {path}. Is this just using regex to replace or something?

**Comment by jklein** [comment] 2015-09-04 09:37
In the anchor you should be using `#{filename}`. See [config-example.json](https://github.com/etsy/hound/blob/master/config-example.json#L45-L51). The code to handle this logic is in [common.js](https://github.com/etsy/hound/blob/master/ui/assets/js/common.js).

**Comment by jklein** [comment] 2015-09-04 09:38
I'm going to close this for now since it seems likely to be a config issue. Feel free to re-open if you have a reproducible case where this isn't working.

**Closed by jklein** 2015-09-04 09:38 UTC
