### ISSUE TITLE
Doesn't load in Firefox 35 on a Mac

### ISSUE THREAD

**Issue by rokcarl** [etsy/Hound#67] opened 2015-02-12 12:42 UTC
I can load [http://localhost:6080/](http://localhost:6080/) in Safari, but not in Firefox 35.0.1 on a Mac saying the connection has timed out. Could be my system at fault here...

**Comment by jklein** [comment] 2015-02-12 14:06
Just tried in Firefox 35.0.1 on my Macbook pro and it works for me. Try in a private window to make sure no extensions are interfering, make sure there's nothing weird in your hosts file, and give it a shot in other  browsers to see if it's really a Firefox specific issue. I'm going to close this, but feel free to reopen if you have concrete steps to reproduce.

**Closed by jklein** 2015-02-12 14:06 UTC
